import Head from 'next/head';
import styles from '../styles/Home.module.css';

// amplify authentication
import { Amplify } from 'aws-amplify';
import { withAuthenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import awsExports from '../src/aws-exports';
Amplify.configure(awsExports);
import { CognitoUser } from "@aws-amplify/auth";


interface UserAttributes {
  sub: string;
  email: string;
  email_verified: boolean;
  name: string;
  phone_number: string;
  phone_number_verified: boolean;
}
interface CognitoUserExt extends CognitoUser {
  attributes: UserAttributes;
}
type CognitoSignOut = () => void;
interface Props {
  user: CognitoUserExt,
  signOut: CognitoSignOut
}

const Home = ({user, signOut}: Props ) => {
  console.log(user.attributes);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>{user.attributes.name}</h2>
        <button onClick={signOut}>Sign out</button>
      </main>
    </div>
  );
};

export default withAuthenticator(Home);
